.class public final Lcom/google/android/gms/games/internal/player/zze;
.super Lcom/google/android/gms/games/internal/zzc;
.source "SourceFile"


# annotations
.annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Class;
    creator = "ProfileCapabilitiesCreator"
.end annotation


# static fields
.field public static final CREATOR:Landroid/os/Parcelable$Creator;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Landroid/os/Parcelable$Creator<",
            "Lcom/google/android/gms/games/internal/player/zze;",
            ">;"
        }
    .end annotation
.end field


# instance fields
.field private final zza:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "forbiddenToHavePlayerProfile"
        id = 0x1
    .end annotation
.end field

.field private final zzb:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "requiresParentPermissionToShareData"
        id = 0x2
    .end annotation
.end field

.field private final zzc:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "hasSettingsControlledByParent"
        id = 0x3
    .end annotation
.end field

.field private final zzd:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "requiresParentPermissionToUsePlayTogether"
        id = 0x4
    .end annotation
.end field

.field private final zze:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "canUseOnlyAutoGeneratedGamerTag"
        id = 0x5
    .end annotation
.end field

.field private final zzf:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "forbiddenToRecordVideo"
        id = 0x6
    .end annotation
.end field

.field private final zzg:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "shouldSeeEquallyWeightedButtonsInConsents"
        id = 0x7
    .end annotation
.end field

.field private final zzh:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "requiresParentConsentToUseAutoSignIn"
        id = 0x8
    .end annotation
.end field

.field private final zzi:Z
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Field;
        getter = "shouldSeeSimplifiedConsentMessages"
        id = 0x9
    .end annotation
.end field


# direct methods
.method static constructor <clinit>()V
    .locals 1

    new-instance v0, Lcom/google/android/gms/games/internal/player/zzf;

    invoke-direct {v0}, Lcom/google/android/gms/games/internal/player/zzf;-><init>()V

    sput-object v0, Lcom/google/android/gms/games/internal/player/zze;->CREATOR:Landroid/os/Parcelable$Creator;

    return-void
.end method

.method public constructor <init>(ZZZZZZZZZ)V
    .locals 0
    .param p1    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x1
        .end annotation
    .end param
    .param p2    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x2
        .end annotation
    .end param
    .param p3    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x3
        .end annotation
    .end param
    .param p4    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x4
        .end annotation
    .end param
    .param p5    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x5
        .end annotation
    .end param
    .param p6    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x6
        .end annotation
    .end param
    .param p7    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x7
        .end annotation
    .end param
    .param p8    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x8
        .end annotation
    .end param
    .param p9    # Z
        .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Param;
            id = 0x9
        .end annotation
    .end param
    .annotation build Lcom/google/android/gms/common/internal/safeparcel/SafeParcelable$Constructor;
    .end annotation

    .line 1
    .line 2
    .line 3
    invoke-direct {p0}, Lcom/google/android/gms/games/internal/zzc;-><init>()V

    .line 4
    .line 5
    iput-boolean p1, p0, Lcom/google/android/gms/games/internal/player/zze;->zza:Z

    .line 6
    .line 7
    iput-boolean p2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzb:Z

    .line 8
    .line 9
    iput-boolean p3, p0, Lcom/google/android/gms/games/internal/player/zze;->zzc:Z

    .line 10
    .line 11
    iput-boolean p4, p0, Lcom/google/android/gms/games/internal/player/zze;->zzd:Z

    .line 12
    .line 13
    iput-boolean p5, p0, Lcom/google/android/gms/games/internal/player/zze;->zze:Z

    .line 14
    .line 15
    iput-boolean p6, p0, Lcom/google/android/gms/games/internal/player/zze;->zzf:Z

    .line 16
    .line 17
    iput-boolean p7, p0, Lcom/google/android/gms/games/internal/player/zze;->zzg:Z

    .line 18
    .line 19
    iput-boolean p8, p0, Lcom/google/android/gms/games/internal/player/zze;->zzh:Z

    .line 20
    .line 21
    iput-boolean p9, p0, Lcom/google/android/gms/games/internal/player/zze;->zzi:Z

    .line 22
    return-void
.end method


# virtual methods
.method public final equals(Ljava/lang/Object;)Z
    .locals 4
    .param p1    # Ljava/lang/Object;
        .annotation build Landroidx/annotation/Nullable;
        .end annotation
    .end param

    .line 1
    .line 2
    instance-of v0, p1, Lcom/google/android/gms/games/internal/player/zze;

    .line 3
    const/4 v1, 0x0

    .line 4
    .line 5
    if-nez v0, :cond_0

    .line 6
    return v1

    .line 7
    :cond_0
    const/4 v0, 0x1

    .line 8
    .line 9
    if-ne p0, p1, :cond_1

    .line 10
    return v0

    .line 11
    .line 12
    :cond_1
    check-cast p1, Lcom/google/android/gms/games/internal/player/zze;

    .line 13
    .line 14
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zza:Z

    .line 15
    .line 16
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zza:Z

    .line 17
    .line 18
    if-ne v2, v3, :cond_2

    .line 19
    .line 20
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzb:Z

    .line 21
    .line 22
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zzb:Z

    .line 23
    .line 24
    if-ne v2, v3, :cond_2

    .line 25
    .line 26
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzc:Z

    .line 27
    .line 28
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zzc:Z

    .line 29
    .line 30
    if-ne v2, v3, :cond_2

    .line 31
    .line 32
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzd:Z

    .line 33
    .line 34
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zzd:Z

    .line 35
    .line 36
    if-ne v2, v3, :cond_2

    .line 37
    .line 38
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zze:Z

    .line 39
    .line 40
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zze:Z

    .line 41
    .line 42
    if-ne v2, v3, :cond_2

    .line 43
    .line 44
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzf:Z

    .line 45
    .line 46
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zzf:Z

    .line 47
    .line 48
    if-ne v2, v3, :cond_2

    .line 49
    .line 50
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzg:Z

    .line 51
    .line 52
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zzg:Z

    .line 53
    .line 54
    if-ne v2, v3, :cond_2

    .line 55
    .line 56
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzh:Z

    .line 57
    .line 58
    iget-boolean v3, p1, Lcom/google/android/gms/games/internal/player/zze;->zzh:Z

    .line 59
    .line 60
    if-ne v2, v3, :cond_2

    .line 61
    .line 62
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzi:Z

    .line 63
    .line 64
    iget-boolean p1, p1, Lcom/google/android/gms/games/internal/player/zze;->zzi:Z

    .line 65
    .line 66
    if-ne v2, p1, :cond_2

    .line 67
    return v0

    .line 68
    :cond_2
    return v1
.end method

.method public final hashCode()I
    .locals 11

    .line 1
    .line 2
    iget-boolean v0, p0, Lcom/google/android/gms/games/internal/player/zze;->zza:Z

    .line 3
    .line 4
    .line 5
    invoke-static {v0}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 6
    move-result-object v0

    .line 7
    .line 8
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzb:Z

    .line 9
    .line 10
    .line 11
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 12
    move-result-object v1

    .line 13
    .line 14
    iget-boolean v2, p0, Lcom/google/android/gms/games/internal/player/zze;->zzc:Z

    .line 15
    .line 16
    .line 17
    invoke-static {v2}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 18
    move-result-object v2

    .line 19
    .line 20
    iget-boolean v3, p0, Lcom/google/android/gms/games/internal/player/zze;->zzd:Z

    .line 21
    .line 22
    .line 23
    invoke-static {v3}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 24
    move-result-object v3

    .line 25
    .line 26
    iget-boolean v4, p0, Lcom/google/android/gms/games/internal/player/zze;->zze:Z

    .line 27
    .line 28
    .line 29
    invoke-static {v4}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 30
    move-result-object v4

    .line 31
    .line 32
    iget-boolean v5, p0, Lcom/google/android/gms/games/internal/player/zze;->zzf:Z

    .line 33
    .line 34
    .line 35
    invoke-static {v5}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 36
    move-result-object v5

    .line 37
    .line 38
    iget-boolean v6, p0, Lcom/google/android/gms/games/internal/player/zze;->zzg:Z

    .line 39
    .line 40
    .line 41
    invoke-static {v6}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 42
    move-result-object v6

    .line 43
    .line 44
    iget-boolean v7, p0, Lcom/google/android/gms/games/internal/player/zze;->zzh:Z

    .line 45
    .line 46
    .line 47
    invoke-static {v7}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 48
    move-result-object v7

    .line 49
    .line 50
    iget-boolean v8, p0, Lcom/google/android/gms/games/internal/player/zze;->zzi:Z

    .line 51
    .line 52
    .line 53
    invoke-static {v8}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 54
    move-result-object v8

    .line 55
    .line 56
    const/16 v9, 0x9

    .line 57
    .line 58
    new-array v9, v9, [Ljava/lang/Object;

    .line 59
    const/4 v10, 0x0

    .line 60
    .line 61
    aput-object v0, v9, v10

    .line 62
    const/4 v0, 0x1

    .line 63
    .line 64
    aput-object v1, v9, v0

    .line 65
    const/4 v0, 0x2

    .line 66
    .line 67
    aput-object v2, v9, v0

    .line 68
    const/4 v0, 0x3

    .line 69
    .line 70
    aput-object v3, v9, v0

    .line 71
    const/4 v0, 0x4

    .line 72
    .line 73
    aput-object v4, v9, v0

    .line 74
    const/4 v0, 0x5

    .line 75
    .line 76
    aput-object v5, v9, v0

    .line 77
    const/4 v0, 0x6

    .line 78
    .line 79
    aput-object v6, v9, v0

    .line 80
    const/4 v0, 0x7

    .line 81
    .line 82
    aput-object v7, v9, v0

    .line 83
    .line 84
    const/16 v0, 0x8

    .line 85
    .line 86
    aput-object v8, v9, v0

    .line 87
    .line 88
    .line 89
    invoke-static {v9}, Lcom/google/android/gms/common/internal/Objects;->hashCode([Ljava/lang/Object;)I

    .line 90
    move-result v0

    .line 91
    return v0
.end method

.method public final toString()Ljava/lang/String;
    .locals 3

    .line 1
    .line 2
    .line 3
    invoke-static {p0}, Lcom/google/android/gms/common/internal/Objects;->toStringHelper(Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 4
    move-result-object v0

    .line 5
    .line 6
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zza:Z

    .line 7
    .line 8
    .line 9
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 10
    move-result-object v1

    .line 11
    .line 12
    const-string v2, "forbiddenToHavePlayerProfile"

    .line 13
    .line 14
    .line 15
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 16
    move-result-object v0

    .line 17
    .line 18
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzb:Z

    .line 19
    .line 20
    .line 21
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 22
    move-result-object v1

    .line 23
    .line 24
    const-string v2, "requiresParentPermissionToShareData"

    .line 25
    .line 26
    .line 27
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 28
    move-result-object v0

    .line 29
    .line 30
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzc:Z

    .line 31
    .line 32
    .line 33
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 34
    move-result-object v1

    .line 35
    .line 36
    const-string v2, "hasSettingsControlledByParent"

    .line 37
    .line 38
    .line 39
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 40
    move-result-object v0

    .line 41
    .line 42
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzd:Z

    .line 43
    .line 44
    .line 45
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 46
    move-result-object v1

    .line 47
    .line 48
    const-string v2, "requiresParentPermissionToUsePlayTogether"

    .line 49
    .line 50
    .line 51
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 52
    move-result-object v0

    .line 53
    .line 54
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zze:Z

    .line 55
    .line 56
    .line 57
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 58
    move-result-object v1

    .line 59
    .line 60
    const-string v2, "canUseOnlyAutoGeneratedGamerTag"

    .line 61
    .line 62
    .line 63
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 64
    move-result-object v0

    .line 65
    .line 66
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzf:Z

    .line 67
    .line 68
    .line 69
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 70
    move-result-object v1

    .line 71
    .line 72
    const-string v2, "forbiddenToRecordVideo"

    .line 73
    .line 74
    .line 75
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 76
    move-result-object v0

    .line 77
    .line 78
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzg:Z

    .line 79
    .line 80
    .line 81
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 82
    move-result-object v1

    .line 83
    .line 84
    const-string v2, "shouldSeeEquallyWeightedButtonsInConsents"

    .line 85
    .line 86
    .line 87
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 88
    move-result-object v0

    .line 89
    .line 90
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzh:Z

    .line 91
    .line 92
    .line 93
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 94
    move-result-object v1

    .line 95
    .line 96
    const-string v2, "requiresParentConsentToUseAutoSignIn"

    .line 97
    .line 98
    .line 99
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 100
    move-result-object v0

    .line 101
    .line 102
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzi:Z

    .line 103
    .line 104
    .line 105
    invoke-static {v1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 106
    move-result-object v1

    .line 107
    .line 108
    const-string v2, "shouldSeeSimplifiedConsentMessages"

    .line 109
    .line 110
    .line 111
    invoke-virtual {v0, v2, v1}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->add(Ljava/lang/String;Ljava/lang/Object;)Lcom/google/android/gms/common/internal/Objects$ToStringHelper;

    .line 112
    move-result-object v0

    .line 113
    .line 114
    .line 115
    invoke-virtual {v0}, Lcom/google/android/gms/common/internal/Objects$ToStringHelper;->toString()Ljava/lang/String;

    .line 116
    move-result-object v0

    .line 117
    return-object v0
.end method

.method public final writeToParcel(Landroid/os/Parcel;I)V
    .locals 2

    .line 1
    .line 2
    .line 3
    invoke-static {p1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->beginObjectHeader(Landroid/os/Parcel;)I

    .line 4
    move-result p2

    .line 5
    const/4 v0, 0x1

    .line 6
    .line 7
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zza:Z

    .line 8
    .line 9
    .line 10
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 11
    const/4 v0, 0x2

    .line 12
    .line 13
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzb:Z

    .line 14
    .line 15
    .line 16
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 17
    const/4 v0, 0x3

    .line 18
    .line 19
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzc:Z

    .line 20
    .line 21
    .line 22
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 23
    const/4 v0, 0x4

    .line 24
    .line 25
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzd:Z

    .line 26
    .line 27
    .line 28
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 29
    const/4 v0, 0x5

    .line 30
    .line 31
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zze:Z

    .line 32
    .line 33
    .line 34
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 35
    const/4 v0, 0x6

    .line 36
    .line 37
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzf:Z

    .line 38
    .line 39
    .line 40
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 41
    const/4 v0, 0x7

    .line 42
    .line 43
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzg:Z

    .line 44
    .line 45
    .line 46
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 47
    .line 48
    const/16 v0, 0x8

    .line 49
    .line 50
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzh:Z

    .line 51
    .line 52
    .line 53
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 54
    .line 55
    const/16 v0, 0x9

    .line 56
    .line 57
    iget-boolean v1, p0, Lcom/google/android/gms/games/internal/player/zze;->zzi:Z

    .line 58
    .line 59
    .line 60
    invoke-static {p1, v0, v1}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->writeBoolean(Landroid/os/Parcel;IZ)V

    .line 61
    .line 62
    .line 63
    invoke-static {p1, p2}, Lcom/google/android/gms/common/internal/safeparcel/SafeParcelWriter;->finishObjectHeader(Landroid/os/Parcel;I)V

    .line 64
    return-void
.end method
